// Aetherium port guard: Minecraft 1.21
// Generated by tools/gen_deltas.py. Run from the repo root after applying the delta:
//   kscript deltas/1.21/build.gradle.kts   (or: kotlinc -script ... / gradle -b ... )
// It re-reads the tree's pins and exits non-zero on any drift, because a port that
// half-applied is worse than one that fails loudly.
@file:Suppress("UNUSED_VARIABLE")

import java.io.File

val expect = mapOf(
    "minecraft_version" to "1.21",
    "java_version" to "21",
    "fabric_loader_version" to "0.16.9",
    "fabric_api_version" to "0.102.0+1.21",
    "neoforge_version" to "21.0.167"
)

val props = File(System.getProperty("user.dir"), "gradle.properties")
if (!props.isFile()) {
    System.err.println("gradle.properties not found under " + System.getProperty("user.dir"))
    kotlin.system.exitProcess(2)
}
var failures = 0
for ((key, want) in expect) {
    val line = props.readLines().firstOrNull { it.startsWith("$key=") }
    val have = line?.substringAfter('=') ?: "<missing>"
    if (have != want) {
        System.err.println("PIN DRIFT $key: expected $want, found $have")
        failures++
    }
}
if (failures == 0) println("pins ok for 1.21")
kotlin.system.exitProcess(if (failures == 0) 0 else 1)
